version: '3.3'
services:
  api:
    container_name: 'calendar-api'
    image: 'calendar-api'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=calendar
      - DB_PW=calendar
      - DB_NAME=calendar-db
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/usr/canlendar-api
      - /usr/canlendar-api/node_modules
    command: npm start

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'calendar-db'
      MYSQL_USER: 'calendar'
      MYSQL_PASSWORD: 'calendar'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - calendar-db:/var/lib/mysql
volumes:
  calendar-db: